spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      naming:
        physical-strategy: com.kivred.web.config.DbNamingStrategy
  main:
    web-application-type: servlet

user:
  token: cE3A6RIjPJSGPPiDxi6z
  ignore-path: >
    /,
    /api/o/free/reg,
    /public/*,
    /swagger-ui/*,
    /v3/api-docs,
    /v3/api-docs/swagger-config

logging:
  level:
    org.hibernate: ERROR
    org.springframework.web: ERROR