spring:
  datasource:
    url: jdbc:h2:mem:kivred
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false